### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by Pzoom522** [ZurichNLP/acl2020-historical-text-normalization#1]
Hi, I came across you paper, which is excellent! Is there any timetable of the code availability? Many thanks!

**Comment by simon-clematide** [comment]
Thanks for your interest. We should have it by the 17th of July.

**Comment by Pzoom522** [comment]
thanks for your reply. looking forward to the code 😃

**Comment by peter-makarov** [comment]
Hi, thanks for your interest! The code is now up, and we will also share the data (language models, word candidate lists derived from wikipedia, model predictions) soon.
